### ISSUE TITLE
Duplicated package

### ISSUE THREAD

**Issue by 1st** [benjohnson/atom-django-templates#1]
As I can see - someone created very similar package to support Django Templates. You can message author to merge your repos to one. It's more good way to have only one copy of Django Templates highlighter.

The package is: https://atom.io/packages/language-python-django-templates

Thanks,

**Comment by benjohnson** [comment]
This will eventually be solved by combining with zacharytamas/atom-django. See: https://github.com/zacharytamas/atom-django/issues/6
