### ISSUE TITLE
All HTML files default to HTML (Django)

### ISSUE THREAD

**Issue by bswank** [benjohnson/atom-django-templates#29]
Thanks for this package! I work regularly in Django writing HTML & CSS and the occasional logic. The highlighting helps a lot.

I've added a portion of the path (and I tried the whole path as well) to the Setting that specifies what need be included in a path for the package to do it's thing. I'm missing something, though, because no matter what I do every HTML file I open defaults to HTML (Django).

**Comment by tristanbiesecker** [comment]
I have the same issue. Did you ever find a fix @bswank?

**Comment by bswank** [comment]
@splitstep Sorry, no. I actually stopped using Atom over this and a few other issues I was having with Emmet and other packages. Moved to Sublime. :)

Closing this issue.
